Develop
Monogramm/ldap-all-for-one-manager pull request #3
Opened 2021-03-13 22:52 UTC by Nathan-Al

> Please provide enough information so that others can review your pull request:

> Explain the **details** for making this change. What existing problem does the pull request solve?

> Screenshots/GIFs

2021-03-14 14:04 UTC, madmath03 requested changes

2021-03-15 14:24 UTC, Nathan-Al commented on app/assets/vue/modules/user/views/ResetPassword.vue
> +</style>
Yes you right, my bad, i fix that.

2021-03-15 14:26 UTC, Nathan-Al commented on app/assets/vue/modules/user/views/UserProfile.vue
> +            Gestion du profile
Sorry but i'm not sure to catch that comment

2021-03-15 17:20 UTC, madmath03 commented on app/assets/vue/modules/user/views/UserProfile.vue
> +            Gestion du profile
1. All comments and git messages must be in English and generally follow what is described in the [Contributing Guidelines](https://github.com/Monogramm/ldap-all-for-one-manager/blob/develop/CONTRIBUTING.md)
2. All texts on frontend must be translated using the Internationalization tools provided in the project (i.e. no hard coded texts on frontend)

2021-03-29 14:53 UTC, closed without merging